version: '2'
services:
    jhipstertest-app:
        image: jhipstertest
        external_links:
            - jhipstertest-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=JHipsterTest
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipstertest-mongodb:
        extends:
            file: mongodb.yml
            service: jhipstertest-mongodb
