version: '2'
services:
    jhipstertest-mongodb:
        container_name: jhipstertest-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/JHipsterTest/mongodb/:/data/db/
